version: '3.8'

services:
  api:
    build: .
    container_name: be-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0.15
    container_name: be-mongodb-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
