version: '3.8'

services:
  api:
    build: .
    container_name: be-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - appnet

  mongodb:
    image: mongo:5.0.15
    container_name: be-mongodb-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - appnet

  redis:
    image: redis:7.2
    container_name: be-redis-1
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  mongodb_data_container:
